language: ruby
rvm:
  - 2.1.1
  - 1.9.3
  - rbx
  - jruby-19mode # JRuby in 1.9 mode

matrix:
  allow_failures:
    - rvm: jruby-19mode # JRuby in 1.9 mode

services:
  - couchdb

script: bundle exec rspec -fd spec/unit_tests/
